debug: false

language: en

# Prevents players from progressing in collections if they are in creative mode
prevent-creative-mode: true

# Always keep at least one alias for each command
command-aliases:
  collections: ["collections", "collection"]

display-components:
  rewards:
    title: "  &7Rewards:&r"
    line: "    {reward}"

level-up-message:
  enabled: true
  message:
    - "&3&m----------------------------------------&r"
    - ' '
    - "  &f&l{collection_name} collection level up &6&l{level}&r"
    - ' '
    - "component:rewards"
    - ' '
    - "&3&m----------------------------------------"

level-up-sound:
  enabled: true
  sound: "ENTITY_PLAYER_LEVELUP"
  volume: 1
  pitch: 1

# These will be default values for all collections
# You can override these values in the collection config
global-level-matchers:
  default:
    interval: 1
    priority: 0
    rewards:
      my-money-reward:
        type: money
        formula: "1000 * {level_raw}^2 - 1000 * {level_raw} + 2000"
        display: "&8+&a{value_formatted}$"
      my-xp-reward:
        type: levels_xp
        formula: "ceil(5 + 5 * ({level_raw} - 1) * (log(1 + {level_raw}) / log(2)))"
        display: "&8+&b{value_formatted} Global XP"

# Don't touch this unless you know what you're doing
config-version: 0