name: AuroraCollections
version: '${version}'
main: gg.auroramc.collections.AuroraCollections
api-version: '1.19'
authors: [ erik_sz ]
folia-supported: true
depend: [ Aurora ]
softdepend:
  - WorldGuard
  - AuroraLevels
  - AuraSkills
  - CustomFishing
  - MythicMobs
  - MythicLib
  - MMOItems

website: https://auroramc.gg

permissions:
  aurora.collections.use:
    description: Allows the player to use the /collections command
    default: true
  aurora.collections.admin.*:
    default: op
    children:
      - aurora.collections.admin.reload
      - aurora.collections.admin.open