triggers: [ block_loot ]
types:
  - "minecraft:birch_log"
  - "minecraft:birch_wood"
  - "minecraft:stripped_birch_log"
  - "minecraft:stripped_birch_wood"

name: "Birch"

menu-item:
  material: BIRCH_LOG

# This defines the levels
# To reach level 1, you need 50
# To reach level 2, you need 100 and so on
requirements:
  - 80
  - 200
  - 500
  - 2000
  - 5000
  - 10000
  - 25000

use-global-level-matchers: true