triggers: [ block_loot ]
types:
  - "minecraft:cherry_log"
  - "minecraft:cherry_wood"
  - "minecraft:stripped_cherry_log"
  - "minecraft:stripped_cherry_wood"

name: "Cherry"

menu-item:
  material: CHERRY_LOG

# This defines the levels
# To reach level 1, you need 50
# To reach level 2, you need 100 and so on
requirements:
  - 80
  - 200
  - 500
  - 2000
  - 5000
  - 10000
  - 25000

use-global-level-matchers: true