triggers: [ block_loot ]
types:
  - "minecraft:dark_oak_log"
  - "minecraft:dark_oak_wood"
  - "minecraft:stripped_dark_oak_log"
  - "minecraft:stripped_dark_oak_wood"

name: "Dark Oak"

menu-item:
  material: DARK_OAK_LOG

# This defines the levels
# To reach level 1, you need 50
# To reach level 2, you need 100 and so on
requirements:
  - 50
  - 100
  - 250
  - 1000
  - 2500
  - 5000
  - 10000

use-global-level-matchers: true