triggers: [ block_loot ]
types:
  - "minecraft:spruce_log"
  - "minecraft:spruce_wood"
  - "minecraft:stripped_spruce_log"
  - "minecraft:stripped_spruce_wood"

name: "Spruce"

menu-item:
  material: SPRUCE_LOG

# This defines the levels
# To reach level 1, you need 50
# To reach level 2, you need 100 and so on
requirements:
  - 80
  - 200
  - 500
  - 2000
  - 5000
  - 10000
  - 25000

use-global-level-matchers: true