triggers: [ harvest ]
types:
  - "minecraft:cocoa_beans"

name: "Cocoa Beans"

menu-item:
  material: COCOA_BEANS

# This defines the levels
# To reach level 1, you need 50
# To reach level 2, you need 100 and so on
requirements:
  - 200
  - 600
  - 1400
  - 2600
  - 3500
  - 4800
  - 8000
  - 11500
  - 15000
  - 20000
  - 25000
  - 33000
  - 40000
  - 50000

use-global-level-matchers: true