triggers: [ harvest ]
types:
  - "minecraft:melon_slice"
  - "minecraft:melon"

name: "Melon"

menu-item:
  material: MELON_SLICE

# This defines the levels
# To reach level 1, you need 50
# To reach level 2, you need 100 and so on
requirements:
  - 300
  - 800
  - 1600
  - 3000
  - 4200
  - 5800
  - 8300
  - 11700
  - 16000
  - 21000
  - 27000
  - 33500
  - 41000
  - 50000

use-global-level-matchers: true