triggers: [ entity_loot ]
types:
  - "minecraft:mutton"
  - "minecraft:cooked_mutton"

name: "Mutton"

menu-item:
  material: MUTTON

# This defines the levels
# To reach level 1, you need 50
# To reach level 2, you need 100 and so on
requirements:
  - 50
  - 200
  - 500
  - 800
  - 1100
  - 2000
  - 2500
  - 3000
  - 5000
  - 8000
  - 10000
  - 15000
  - 20000

use-global-level-matchers: true