triggers: [ harvest, block_loot ]
types:
  - "minecraft:wheat_seeds"

name: "Seeds"

menu-item:
  material: WHEAT_SEEDS

# This defines the levels
# To reach level 1, you need 50
# To reach level 2, you need 100 and so on
requirements:
  - 300
  - 800
  - 1600
  - 3000
  - 5000
  - 8000
  - 10000
  - 15000
  - 20000
  - 28000
  - 35000
  - 40000
  - 50000
  - 60000

use-global-level-matchers: true